package facilitator

// Facilitator error / invalidReason constants for Hedera exact (V2).
const (
	ErrUnsupportedScheme              = "unsupported_scheme"
	ErrNetworkMismatch                = "network_mismatch"
	ErrInvalidAsset                   = "invalid_asset"
	ErrInvalidAmount                  = "invalid_amount"
	ErrMissingFeePayer                = "invalid_exact_hedera_payload_missing_fee_payer"
	ErrFeePayerNotManaged             = "fee_payer_not_managed_by_facilitator"
	ErrPayToAliasNotAllowed           = "invalid_exact_hedera_payload_pay_to_alias_not_allowed"
	ErrInvalidPayTo                   = "invalid_exact_hedera_payload_pay_to"
	ErrTransactionDecode              = "invalid_exact_hedera_payload_transaction_could_not_be_decoded"
	ErrTransactionInvalidShape        = "invalid_exact_hedera_payload_transaction_invalid_shape"
	ErrReplay                         = "invalid_exact_hedera_payload_replay"
	ErrFeePayerMismatch               = "invalid_exact_hedera_payload_fee_payer_mismatch"
	ErrNonTransferOps                 = "invalid_exact_hedera_payload_contains_non_transfer_ops"
	ErrHbarSumNonZero                 = "invalid_exact_hedera_payload_hbar_sum_non_zero"
	ErrFeePayerTransferringHbar       = "invalid_exact_hedera_payload_fee_payer_transferring_hbar"
	ErrUnexpectedHbarTransfers        = "invalid_exact_hedera_payload_unexpected_hbar_transfers"
	ErrAssetMismatch                  = "invalid_exact_hedera_payload_asset_mismatch"
	ErrAssetSumNonZero                = "invalid_exact_hedera_payload_asset_sum_non_zero"
	ErrFeePayerTransferringFunds      = "invalid_exact_hedera_payload_fee_payer_transferring_funds"
	ErrAmountMismatch                 = "invalid_exact_hedera_payload_amount_mismatch"
	ErrExtraPositiveTransfers         = "invalid_exact_hedera_payload_extra_positive_transfers"
	ErrSignatureInvalid               = "invalid_exact_hedera_payload_signature_invalid"
	ErrPreflightFailed                = "invalid_exact_hedera_payload_preflight_failed"
	ErrAcceptedMismatch               = "accepted_payment_requirements_mismatch"
	ErrInvalidAssetTransferMethod     = "invalid_exact_hedera_asset_transfer_method"
	ErrUnsupportedAssetTransferMethod = "invalid_exact_hedera_unsupported_asset_transfer_method"
	ErrInvalidX402Version             = "invalid_x402_version"
	ErrVerificationFailed             = "verification_failed"
	ErrTransactionFailed              = "transaction_failed"
)
