import { PaymentPayload } from "@x402/core/types";
import { createHash } from "crypto";
import { IdempotencyKeyGenerator, KeyGeneratorFn } from "./types";

/**
 * Default implementation of IdempotencyKeyGenerator using SHA-256 hash
 * of payment parameters to ensure deterministic key generation.
 */
export class DefaultIdempotencyKeyGenerator implements IdempotencyKeyGenerator {
  /**
   * Generate a deterministic idempotency key from payment payload.
   *
   * The key is generated by hashing critical payment parameters:
   * - accepted.scheme: Payment scheme identifier
   * - accepted.network: Network identifier
   * - accepted.payTo: Recipient address
   * - accepted.amount: Payment amount
   * - accepted.maxTimeoutSeconds: Timeout value
   * - payload: Network-specific payment data (contains nonce, validUntil, etc.)
   *
   * @param payload - Payment payload containing all payment information
   * @returns Base64url-encoded hash prefixed with 'idk_'
   */
  generateKey(payload: PaymentPayload): string {
    // Extract critical parameters for hashing
    const params = {
      scheme: payload.accepted.scheme,
      network: payload.accepted.network,
      payTo: payload.accepted.payTo,
      amount: payload.accepted.amount,
      maxTimeoutSeconds: payload.accepted.maxTimeoutSeconds,
      // Include the full payload which contains nonce, validUntil, signatures, etc.
      payload: payload.payload,
    };

    // Create deterministic hash
    const hash = createHash("sha256").update(JSON.stringify(params)).digest("base64url");

    return `idk_${hash}`;
  }
}

/**
 * Create a custom idempotency key generator from a function.
 *
 * @param generatorFn - Function that takes PaymentPayload and returns a string key
 * @returns IdempotencyKeyGenerator instance
 *
 * @example
 * ```typescript
 * const customGenerator = createIdempotencyKeyGenerator((payload) => {
 *   return `custom_${payload.accepted.payTo}_${Date.now()}`;
 * });
 * ```
 */
export function createIdempotencyKeyGenerator(
  generatorFn: KeyGeneratorFn,
): IdempotencyKeyGenerator {
  return {
    generateKey: generatorFn,
  };
}

/**
 * Default idempotency key generator instance
 */
export const defaultIdempotencyKeyGenerator = new DefaultIdempotencyKeyGenerator();
