"""Constants for x402 MCP integration."""

MCP_PAYMENT_META_KEY = "x402/payment"
MCP_PAYMENT_RESPONSE_META_KEY = "x402/payment-response"

DEFAULT_PROBE_TIMEOUT_SECONDS = 300
DEFAULT_ACCEPT_TIMEOUT_SECONDS = 300
DEFAULT_MAX_REQUEST_TIMEOUT_SECONDS = 600
MAX_READ_TIMEOUT_SECONDS = 2**31 - 1
