packages:
  - "facilitators/*"
  - "facilitators/external-proxies/*"
  - "facilitators/external-proxies/local/*"
  - "servers/*"
  - "clients/*"
  - "clients/external/*"
  - "legacy/servers/*"
  - "legacy/clients/*"
  - "../typescript/packages/*"
  - "../typescript/packages/http/*"
  - "../typescript/packages/mechanisms/*"
  - "../typescript/packages/legacy/*"
minimumReleaseAge: 4320 # Only install package versions that have been published for at least 3 days.
minimumReleaseAgeStrict: false
allowBuilds:
  '@coinbase/x402': true # Required for /external-proxies/* CDP testing due to post-install script that prints TOS
  bufferutil: true
  esbuild: true
  keccak: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
