let cachedTemplate: string | null = null;

/**
 * Lazily loads the pre-built Stellar paywall template generated by
 * `src/stellar/build.ts`. Returns null when the template has not been built.
 *
 * @returns The Stellar paywall HTML template, or null if unavailable
 */
export function getStellarTemplate(): string | null {
  if (cachedTemplate !== null) {
    return cachedTemplate;
  }

  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const template = require("./gen/template");
    cachedTemplate = template.STELLAR_PAYWALL_TEMPLATE;
    return cachedTemplate;
  } catch {
    return null;
  }
}
