"""x402 Extensions - Optional extensions for the x402 payment protocol.

This module provides optional extensions that enhance the x402 payment protocol
with additional functionality like resource discovery and cataloging.
"""

from .bazaar import (
    BAZAAR,
    BodyDiscoveryExtension,
    BodyDiscoveryInfo,
    BodyInput,
    BodyMethods,
    BodyType,
    DeclareBodyDiscoveryConfig,
    DeclareQueryDiscoveryConfig,
    DiscoveredResource,
    DiscoveryExtension,
    DiscoveryInfo,
    OutputConfig,
    OutputInfo,
    QueryDiscoveryExtension,
    QueryDiscoveryInfo,
    QueryInput,
    QueryParamMethods,
    bazaar_resource_server_extension,
    declare_discovery_extension,
    extract_discovery_info,
    extract_discovery_info_from_extension,
    validate_and_extract,
    validate_discovery_extension,
)
from .bazaar import (
    ValidationResult as BazaarValidationResult,
)

# Create alias for backward compatibility
ValidationResult = BazaarValidationResult

from .payment_identifier import (  # noqa: E402
    PAYMENT_ID_MAX_LENGTH,
    PAYMENT_ID_MIN_LENGTH,
    PAYMENT_ID_PATTERN,
    PAYMENT_IDENTIFIER,
    PaymentIdentifierExtension,
    PaymentIdentifierInfo,
    PaymentIdentifierSchema,
    PaymentIdentifierValidationResult,
    append_payment_identifier_to_extensions,
    declare_payment_identifier_extension,
    extract_and_validate_payment_identifier,
    extract_payment_identifier,
    generate_payment_id,
    has_payment_identifier,
    is_payment_identifier_extension,
    is_payment_identifier_required,
    is_valid_payment_id,
    payment_identifier_resource_server_extension,
    payment_identifier_schema,
    validate_payment_identifier,
    validate_payment_identifier_requirement,
)
from .sign_in_with_x import (  # noqa: E402
    SIGN_IN_WITH_X,
    SOLANA_DEVNET,
    SOLANA_MAINNET,
    SOLANA_TESTNET,
    CompleteSIWxInfo,
    CreateSIWxClientExtensionOptions,
    CreateSIWxHookOptions,
    CreateSIWxResourceServerExtensionOptions,
    DeclareSIWxOptions,
    EVMMessageVerifier,
    InMemorySIWxStorage,
    SignatureScheme,
    SignatureType,
    SIWxExtension,
    SIWxExtensionInfo,
    SIWxExtensionSchema,
    SIWxHookEvent,
    SIWxPayload,
    SIWxSigner,
    SIWxStorage,
    SIWxValidationOptions,
    SIWxValidationResult,
    SIWxVerifyOptions,
    SIWxVerifyResult,
    SupportedChain,
    build_siwx_schema,
    create_siwx_client_extension,
    create_siwx_client_hook,
    create_siwx_message,
    create_siwx_payload,
    create_siwx_request_hook,
    create_siwx_resource_server_extension,
    create_siwx_settle_hook,
    declare_siwx_extension,
    decode_base58,
    encode_base58,
    encode_siwx_header,
    extract_evm_chain_id,
    extract_solana_chain_reference,
    format_siwe_message,
    format_siws_message,
    get_evm_address,
    get_signature_type,
    get_solana_address,
    is_evm_signer,
    is_solana_signer,
    parse_siwx_header,
    sign_evm_message,
    sign_solana_message,
    validate_siwx_message,
    verify_evm_signature,
    verify_siwx_signature,
    verify_solana_signature,
)

__all__ = [
    # Constants
    "BAZAAR",
    # Method types
    "QueryParamMethods",
    "BodyMethods",
    "BodyType",
    # Input types
    "QueryInput",
    "BodyInput",
    "OutputInfo",
    # Discovery info types
    "QueryDiscoveryInfo",
    "BodyDiscoveryInfo",
    "DiscoveryInfo",
    # Extension types
    "QueryDiscoveryExtension",
    "BodyDiscoveryExtension",
    "DiscoveryExtension",
    # Config types
    "DeclareQueryDiscoveryConfig",
    "DeclareBodyDiscoveryConfig",
    "OutputConfig",
    # Result types
    "ValidationResult",  # From bazaar (for backward compatibility)
    "BazaarValidationResult",  # From bazaar (alias for explicit usage)
    "PaymentIdentifierValidationResult",  # From payment_identifier
    "DiscoveredResource",
    # Server extension
    "bazaar_resource_server_extension",
    # Functions
    "declare_discovery_extension",
    "validate_discovery_extension",
    "extract_discovery_info",
    "extract_discovery_info_from_extension",
    "validate_and_extract",
    # Payment Identifier constants
    "PAYMENT_IDENTIFIER",
    "PAYMENT_ID_MIN_LENGTH",
    "PAYMENT_ID_MAX_LENGTH",
    "PAYMENT_ID_PATTERN",
    # Payment Identifier types
    "PaymentIdentifierInfo",
    "PaymentIdentifierExtension",
    "PaymentIdentifierSchema",
    # Payment Identifier schema
    "payment_identifier_schema",
    # Payment Identifier utils
    "generate_payment_id",
    "is_valid_payment_id",
    # Payment Identifier client functions
    "append_payment_identifier_to_extensions",
    # Payment Identifier server functions
    "declare_payment_identifier_extension",
    "payment_identifier_resource_server_extension",
    # Payment Identifier validation functions
    "is_payment_identifier_extension",
    "validate_payment_identifier",
    "extract_payment_identifier",
    "extract_and_validate_payment_identifier",
    "has_payment_identifier",
    "is_payment_identifier_required",
    "validate_payment_identifier_requirement",
    "PaymentIdentifierValidationResult",
    "BazaarValidationResult",
    # Sign-In-With-X constants
    "SIGN_IN_WITH_X",
    "SOLANA_MAINNET",
    "SOLANA_DEVNET",
    "SOLANA_TESTNET",
    # Sign-In-With-X types
    "SIWxExtension",
    "SIWxExtensionInfo",
    "SIWxExtensionSchema",
    "SIWxPayload",
    "DeclareSIWxOptions",
    "SignatureScheme",
    "SignatureType",
    "SupportedChain",
    "SIWxValidationResult",
    "SIWxValidationOptions",
    "SIWxVerifyResult",
    "EVMMessageVerifier",
    "SIWxVerifyOptions",
    "CompleteSIWxInfo",
    "SIWxHookEvent",
    "SIWxStorage",
    "InMemorySIWxStorage",
    "SIWxSigner",
    # Sign-In-With-X server
    "declare_siwx_extension",
    "create_siwx_resource_server_extension",
    "CreateSIWxResourceServerExtensionOptions",
    "parse_siwx_header",
    "validate_siwx_message",
    "verify_siwx_signature",
    "build_siwx_schema",
    # Sign-In-With-X client
    "create_siwx_message",
    "create_siwx_payload",
    "encode_siwx_header",
    "create_siwx_client_extension",
    "CreateSIWxClientExtensionOptions",
    "create_siwx_client_hook",
    "create_siwx_settle_hook",
    "create_siwx_request_hook",
    "CreateSIWxHookOptions",
    "get_signature_type",
    # Sign-In-With-X chain utils
    "format_siwe_message",
    "verify_evm_signature",
    "extract_evm_chain_id",
    "is_evm_signer",
    "format_siws_message",
    "verify_solana_signature",
    "decode_base58",
    "encode_base58",
    "extract_solana_chain_reference",
    "is_solana_signer",
    "get_evm_address",
    "get_solana_address",
    "sign_evm_message",
    "sign_solana_message",
]
