export const ERR_INVALID_SIGNATURE = "ERR_INVALID_SIGNATURE";
export const ERR_PAYMENT_EXPIRED = "ERR_PAYMENT_EXPIRED";
export const ERR_WRONG_RECIPIENT = "ERR_WRONG_RECIPIENT";
export const ERR_WRONG_TOKEN = "ERR_WRONG_TOKEN";
export const ERR_AMOUNT_MISMATCH = "ERR_AMOUNT_MISMATCH";
export const ERR_REPLAY = "ERR_REPLAY";
export const ERR_MISSING_SETTLEMENT_DATA = "ERR_MISSING_SETTLEMENT_DATA";
export const ERR_SETTLEMENT_FAILED = "ERR_SETTLEMENT_FAILED";
