/**
 * Bazaar extension extraction: pulls input/output schemas from bazaar discovery data.
 */
import type { JsonSchemaProperty } from "./schemas";

/**
 * Schemas extracted from a bazaar discovery extension declaration.
 */
export interface BazaarSchemas {
  inputSchema?: JsonSchemaProperty;
  outputSchema?: JsonSchemaProperty;
  pathParamsSchema?: JsonSchemaProperty;
}

/**
 * Safely access a nested object property by key, returning typed result or undefined.
 */
function getNestedObject(obj: unknown, key: string): Record<string, unknown> | undefined {
  if (obj !== null && typeof obj === "object" && key in (obj as Record<string, unknown>)) {
    const value = (obj as Record<string, unknown>)[key];
    if (value !== null && typeof value === "object") {
      return value as Record<string, unknown>;
    }
  }
  return undefined;
}

/**
 * Extract input/output/pathParams schemas from a bazaar discovery extension.
 *
 * Reads from the `schema` section (JSON Schema declarations) which is always
 * generated by `declareDiscoveryExtension`. This is preferred over the `info`
 * section which only contains example values.
 */
export function extractBazaarSchemas(extensions?: Record<string, unknown>): BazaarSchemas {
  if (!extensions || !("bazaar" in extensions)) return {};

  const bazaar = getNestedObject(extensions, "bazaar");
  if (!bazaar) return {};

  const schema = getNestedObject(bazaar, "schema");
  if (!schema) return {};

  const result: BazaarSchemas = {};

  const schemaProps = getNestedObject(schema, "properties");
  if (!schemaProps) return result;

  const inputProp = getNestedObject(schemaProps, "input");
  if (inputProp) {
    const inputFields = getNestedObject(inputProp, "properties");
    if (inputFields) {
      if (inputFields.queryParams) {
        result.inputSchema = inputFields.queryParams as JsonSchemaProperty;
      }
      if (inputFields.body) {
        result.inputSchema = inputFields.body as JsonSchemaProperty;
      }
      if (inputFields.pathParams) {
        result.pathParamsSchema = inputFields.pathParams as JsonSchemaProperty;
      }
    }
  }

  const outputProp = getNestedObject(schemaProps, "output");
  if (outputProp) {
    result.outputSchema = outputProp as JsonSchemaProperty;
  }

  return result;
}
