"""Implementation budgets for untrusted Cardano payloads and provider work."""

MAX_CARDANO_TRANSACTION_BYTES = 64 * 1024
MAX_CARDANO_TRANSACTION_INPUTS = 256
MAX_CARDANO_INPUT_LOOKUP_CONCURRENCY = 8
MAX_CARDANO_SCRIPT_BYTES = 64 * 1024
MAX_CARDANO_DATUM_BYTES = 64 * 1024
MAX_CARDANO_SCRIPT_PARAMETERS = 64
MAX_CARDANO_SCRIPT_PARAMETER_BYTES = 64 * 1024
MAX_MASUMI_COMMITMENT_PARTS = 32
MAX_MASUMI_COMMITMENT_CONTENT_BYTES = 1024 * 1024
MAX_MASUMI_ADMIN_KEYS = 64
MAX_MASUMI_IDENTIFIER_COMPRESSED_BYTES = 8 * 1024
MAX_MASUMI_IDENTIFIER_TEXT_CHARS = 32 * 1024
MAX_MASUMI_COSE_BYTES = 16 * 1024
MAX_MASUMI_SCRIPT_HASH_CACHE_ENTRIES = 256
DEFAULT_CARDANO_PROVIDER_TIMEOUT_MS = 10_000
