/** Generate the vendored payment-channels TypeScript client from the pinned IDL. */

import type { AnchorIdl } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import { createFromJson } from "codama";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const repositoryDir = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);
const packageDir = path.join(
  repositoryDir,
  "typescript",
  "packages",
  "mechanisms",
  "svm",
);
const idlPath = path.join(packageDir, "idl", "payment-channels.json");
const outputDir = path.join(packageDir, "src", "payment-channels", "generated");

type CodamaEnum = {
  name: string;
  type: {
    kind: "enumTypeNode";
    variants: { discriminator?: number; name: string }[];
  };
};

type CodamaRoot = {
  program: {
    definedTypes: ({ name: string; type: { kind: string } } | CodamaEnum)[];
    publicKey: string;
  };
};

if (!fs.existsSync(idlPath)) {
  throw new Error(`payment-channels IDL not found at ${idlPath}`);
}

const idl = JSON.parse(fs.readFileSync(idlPath, "utf8")) as AnchorIdl;
const codama = createFromJson(JSON.stringify(idl));
const temporaryPackage = fs.mkdtempSync(
  path.join(os.tmpdir(), "x402-payment-channels-"),
);

const formatGeneratedTree = async (directory: string): Promise<void> => {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const filename = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await formatGeneratedTree(filename);
    } else if (entry.name.endsWith(".ts")) {
      const config = (await resolveConfig(filename)) ?? {};
      const source = fs.readFileSync(filename, "utf8");
      fs.writeFileSync(
        filename,
        await format(source, { ...config, filepath: filename }),
      );
    }
  }
};

const upperFirst = (value: string): string =>
  value.charAt(0).toUpperCase() + value.slice(1);

/** Preserve explicit enum values that the JS renderer currently emits as implicit ordinals. */
const applyEnumDiscriminants = (directory: string, root: CodamaRoot): void => {
  for (const definedType of root.program.definedTypes) {
    if (definedType.type.kind !== "enumTypeNode") continue;
    const enumType = definedType as CodamaEnum;
    const filename = path.join(directory, "types", `${enumType.name}.ts`);
    let source = fs.readFileSync(filename, "utf8");

    for (const [index, variant] of enumType.type.variants.entries()) {
      const discriminator = variant.discriminator ?? index;
      const implicit = `  ${upperFirst(variant.name)},`;
      const explicit = `  ${upperFirst(variant.name)} = ${discriminator},`;
      if (!source.includes(implicit)) {
        throw new Error(
          `Codama enum variant not found in ${filename}: ${implicit.trim()}`,
        );
      }
      source = source.replace(implicit, explicit);
    }

    fs.writeFileSync(filename, source);
  }
};

/** Keep the vendored client compatible with the package's Kit >=5 peer range. */
const renderProgramAddressOnly = (
  directory: string,
  root: CodamaRoot,
): void => {
  const filename = path.join(directory, "programs", "paymentChannels.ts");
  fs.writeFileSync(
    filename,
    `/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead rerun the payment-channels generator.
 */

import type { Address } from "@solana/kit";

export const PAYMENT_CHANNELS_PROGRAM_ADDRESS =
  "${root.program.publicKey}" as Address<"${root.program.publicKey}">;
`,
  );
};

/** Replace parser-only Kit 6 error constants so generated clients keep the package's Kit 5 peer. */
const applyKit5Compatibility = (directory: string): void => {
  const instructionsDir = path.join(directory, "instructions");
  for (const entry of fs.readdirSync(instructionsDir, {
    withFileTypes: true,
  })) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const filename = path.join(instructionsDir, entry.name);
    let source = fs.readFileSync(filename, "utf8");
    if (
      !source.includes(
        "SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS",
      )
    ) {
      continue;
    }
    source = source
      .replace(
        /^\s*SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,\n/m,
        "",
      )
      .replace(/^\s*SolanaError,\n/m, "")
      .replace(
        /throw new SolanaError\(\s*SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,\s*\{\s*actualAccountMetas: instruction\.accounts\.length,\s*expectedAccountMetas: (\d+),\s*\},?\s*\);/g,
        (_, expected: string) =>
          `throw new Error(\`insufficient account metas: expected ${expected}, got \${instruction.accounts.length}\`);`,
      );
    if (
      source.includes(
        "SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS",
      )
    ) {
      throw new Error(
        `Kit 5 compatibility transform incomplete for ${filename}`,
      );
    }
    fs.writeFileSync(filename, source);
  }
};

try {
  await codama.accept(renderVisitor(temporaryPackage, { formatCode: true }));
  const rendered = path.join(temporaryPackage, "src", "generated");
  if (!fs.existsSync(rendered)) {
    throw new Error(`Codama output not found at ${rendered}`);
  }

  const root = idl as unknown as CodamaRoot;
  applyEnumDiscriminants(rendered, root);
  renderProgramAddressOnly(rendered, root);
  applyKit5Compatibility(rendered);
  fs.rmSync(outputDir, { force: true, recursive: true });
  fs.cpSync(rendered, outputDir, { recursive: true });
  await formatGeneratedTree(outputDir);
} finally {
  fs.rmSync(temporaryPackage, { force: true, recursive: true });
}

console.log(
  `Generated payment-channels client in ${path.relative(packageDir, outputDir)}`,
);
