#!/usr/bin/env python3
"""Regenerate .github/labeler.yml network labels from .github/labeler-networks.json.

Run from the repository root:

    python3 scripts/generate-labeler-networks.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

BEGIN = "# BEGIN GENERATED NETWORK LABELS"
END = "# END GENERATED NETWORK LABELS"
SCRIPT = "python3 scripts/generate-labeler-networks.py"


def network_paths(network: str) -> list[str]:
    return [
        f"typescript/packages/mechanisms/{network}/**",
        f"go/mechanisms/{network}/**",
        f"go/signers/{network}/**",
        f"python/x402/mechanisms/{network}/**",
        f"specs/schemes/**/scheme_*_{network}.md",
    ]


def render_network_label(network: str) -> str:
    paths = "\n".join(f"          - '{path}'" for path in network_paths(network))
    return f"""{network}:
  - changed-files:
      - any-glob-to-any-file:
{paths}"""


def render_network_section(networks: list[str]) -> str:
    lines = [
        BEGIN,
        "# Generated by scripts/generate-labeler-networks.py — do not edit by hand.",
        f"# Regenerate: {SCRIPT}",
        "# SDK mechanisms (ts/go/py) + scheme_*_<network>.md specs.",
        *[render_network_label(network) for network in networks],
        END,
    ]
    return "\n".join(lines)


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    config_path = repo_root / ".github" / "labeler-networks.json"
    labeler_path = repo_root / ".github" / "labeler.yml"

    config = json.loads(config_path.read_text(encoding="utf-8"))
    networks = config.get("networks")
    if not isinstance(networks, list) or not networks:
        raise SystemExit("`.github/labeler-networks.json` must define a non-empty `networks` array")

    labeler = labeler_path.read_text(encoding="utf-8")
    generated = render_network_section(networks)
    pattern = re.compile(re.escape(BEGIN) + r"[\s\S]*?" + re.escape(END), re.MULTILINE)

    if not pattern.search(labeler):
        raise SystemExit(f"Missing {BEGIN} / {END} markers in .github/labeler.yml")

    labeler_path.write_text(pattern.sub(generated, labeler), encoding="utf-8")
    print(f"Updated network labels for: {', '.join(networks)}")


if __name__ == "__main__":
    try:
        main()
    except SystemExit as exc:
        if exc.code:
            sys.exit(exc.code)
