"""Error code constants for the batch-settlement EVM scheme.

Strings are part of the wire contract and must match exactly across SDKs.
"""

ERR_INVALID_SCHEME = "invalid_batch_settlement_evm_scheme"
ERR_NETWORK_MISMATCH = "invalid_batch_settlement_evm_network_mismatch"
ERR_MISSING_EIP712_DOMAIN = "invalid_batch_settlement_evm_missing_eip712_domain"
ERR_INVALID_PAYLOAD_TYPE = "invalid_batch_settlement_evm_payload_type"

ERR_CHANNEL_NOT_FOUND = "invalid_batch_settlement_evm_channel_not_found"
ERR_CHANNEL_ID_MISMATCH = "invalid_batch_settlement_evm_channel_id_mismatch"
ERR_CHANNEL_STATE_READ_FAILED = "invalid_batch_settlement_evm_channel_state_read_failed"

ERR_RECEIVER_MISMATCH = "invalid_batch_settlement_evm_receiver_mismatch"
ERR_RECEIVER_AUTHORIZER_MISMATCH = "invalid_batch_settlement_evm_receiver_authorizer_mismatch"
ERR_AUTHORIZER_ADDRESS_MISMATCH = "invalid_batch_settlement_evm_authorizer_address_mismatch"
ERR_TOKEN_MISMATCH = "invalid_batch_settlement_evm_token_mismatch"
ERR_WITHDRAW_DELAY_MISMATCH = "invalid_batch_settlement_evm_withdraw_delay_mismatch"
ERR_WITHDRAW_DELAY_OUT_OF_RANGE = "invalid_batch_settlement_evm_withdraw_delay_out_of_range"

ERR_INVALID_VOUCHER_SIGNATURE = "invalid_batch_settlement_evm_voucher_signature"
ERR_CUMULATIVE_EXCEEDS_BALANCE = "invalid_batch_settlement_evm_cumulative_exceeds_balance"
ERR_CUMULATIVE_AMOUNT_BELOW_CLAIMED = "invalid_batch_settlement_evm_cumulative_below_claimed"
ERR_CUMULATIVE_AMOUNT_MISMATCH = "invalid_batch_settlement_evm_cumulative_amount_mismatch"

ERR_INSUFFICIENT_BALANCE = "invalid_batch_settlement_evm_insufficient_balance"

ERR_DEPOSIT_PAYLOAD = "invalid_batch_settlement_evm_deposit_payload"
ERR_DEPOSIT_SIMULATION_FAILED = "invalid_batch_settlement_evm_deposit_simulation_failed"
ERR_DEPOSIT_TRANSACTION_FAILED = "invalid_batch_settlement_evm_deposit_transaction_failed"

ERR_VOUCHER_PAYLOAD = "invalid_batch_settlement_evm_voucher_payload"

ERR_CLAIM_PAYLOAD = "invalid_batch_settlement_evm_claim_payload"
ERR_CLAIM_SIMULATION_FAILED = "invalid_batch_settlement_evm_claim_simulation_failed"
ERR_CLAIM_TRANSACTION_FAILED = "invalid_batch_settlement_evm_claim_transaction_failed"

ERR_SETTLE_PAYLOAD = "invalid_batch_settlement_evm_settle_payload"
ERR_SETTLE_SIMULATION_FAILED = "invalid_batch_settlement_evm_settle_simulation_failed"
ERR_SETTLE_TRANSACTION_FAILED = "invalid_batch_settlement_evm_settle_transaction_failed"
ERR_NOTHING_TO_SETTLE = "invalid_batch_settlement_evm_nothing_to_settle"
ERR_UNKNOWN_SETTLE_ACTION = "invalid_batch_settlement_evm_unknown_settle_action"

ERR_REFUND_PAYLOAD = "invalid_batch_settlement_evm_refund_payload"
ERR_REFUND_SIMULATION_FAILED = "invalid_batch_settlement_evm_refund_simulation_failed"
ERR_REFUND_TRANSACTION_FAILED = "invalid_batch_settlement_evm_refund_transaction_failed"
ERR_REFUND_AMOUNT_INVALID = "invalid_batch_settlement_evm_refund_amount_invalid"
ERR_REFUND_NO_BALANCE = "invalid_batch_settlement_evm_refund_no_balance"

ERR_VALID_AFTER_IN_FUTURE = "invalid_batch_settlement_evm_payload_authorization_valid_after"
ERR_VALID_BEFORE_EXPIRED = "invalid_batch_settlement_evm_payload_authorization_valid_before"
ERR_INVALID_RECEIVE_AUTHORIZATION_SIGNATURE = (
    "invalid_batch_settlement_evm_receive_authorization_signature"
)
ERR_ERC3009_AUTHORIZATION_REQUIRED = "invalid_batch_settlement_evm_erc3009_authorization_required"

ERR_PERMIT2_AUTHORIZATION_REQUIRED = "invalid_batch_settlement_evm_permit2_authorization_required"
ERR_PERMIT2_INVALID_SPENDER = "invalid_batch_settlement_evm_permit2_invalid_spender"
ERR_PERMIT2_AMOUNT_MISMATCH = "invalid_batch_settlement_evm_permit2_amount_mismatch"
ERR_PERMIT2_DEADLINE_EXPIRED = "invalid_batch_settlement_evm_permit2_deadline_expired"
ERR_PERMIT2_INVALID_SIGNATURE = "invalid_batch_settlement_evm_permit2_invalid_signature"
ERR_PERMIT2_ALLOWANCE_REQUIRED = "invalid_batch_settlement_evm_permit2_allowance_required"

ERR_EIP2612_AMOUNT_MISMATCH = "invalid_batch_settlement_evm_eip2612_amount_mismatch"
ERR_EIP2612_OWNER_MISMATCH = "invalid_batch_settlement_evm_eip2612_owner_mismatch"
ERR_EIP2612_ASSET_MISMATCH = "invalid_batch_settlement_evm_eip2612_asset_mismatch"
ERR_EIP2612_SPENDER_MISMATCH = "invalid_batch_settlement_evm_eip2612_spender_mismatch"
ERR_EIP2612_DEADLINE_EXPIRED = "invalid_batch_settlement_evm_eip2612_deadline_expired"
ERR_EIP2612_INVALID_FORMAT = "invalid_batch_settlement_evm_eip2612_invalid_format"
ERR_EIP2612_INVALID_SIGNATURE = "invalid_batch_settlement_evm_eip2612_invalid_signature"

ERR_ERC20_APPROVAL_UNAVAILABLE = "invalid_batch_settlement_evm_erc20_approval_unavailable"
ERR_ERC20_APPROVAL_INVALID_FORMAT = "invalid_batch_settlement_evm_erc20_approval_invalid_format"
ERR_ERC20_APPROVAL_FROM_MISMATCH = "invalid_batch_settlement_evm_erc20_approval_from_mismatch"
ERR_ERC20_APPROVAL_ASSET_MISMATCH = "invalid_batch_settlement_evm_erc20_approval_asset_mismatch"
ERR_ERC20_APPROVAL_WRONG_SPENDER = "invalid_batch_settlement_evm_erc20_approval_wrong_spender"
ERR_ERC20_APPROVAL_BROADCAST_FAILED = "invalid_batch_settlement_evm_erc20_approval_broadcast_failed"

ERR_RPC_READ_FAILED = "invalid_batch_settlement_evm_rpc_read_failed"
ERR_WAIT_FOR_RECEIPT_FAILED = "invalid_batch_settlement_evm_wait_for_receipt_failed"
ERR_TRANSACTION_REVERTED = "invalid_batch_settlement_evm_transaction_reverted"

# Server-emitted lifecycle reasons
ERR_CHANNEL_BUSY = "invalid_batch_settlement_evm_channel_busy"
ERR_CHARGE_EXCEEDS_SIGNED_CUMULATIVE = (
    "invalid_batch_settlement_evm_charge_exceeds_signed_cumulative"
)
ERR_MISSING_CHANNEL = "invalid_batch_settlement_evm_missing_channel"
